import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import ExternalSiteCard from '@/common/ExternalSiteCard'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const externalSite = [
    {
    name: "Discord",
    url: "https://discord.gg/wJKU5QEG6w",
    logo:"/discord-logo-1-1.png",
    imageAlt:"discord logo",
    }]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <div>テムタン　ピチャモン（Theamtun, Phichamon）</div>
          <div>2000年生まれ　チョンブリー県、タイ</div>
          <div>長岡技術科学大学 情報・経営システム工学分野 修士 1 年</div>
          <div>泰日工業大学 コンピューター工学部 卒業</div>
        </div>
        <Image
            src="/proflie.jpg"
            alt="profile image"
            width={180}
            height={180}
            priority
          />
        <h2>外部サイト</h2>
        <div>
          {externalSite.map((website) => 
          <ExternalSiteCard
          siteName='Discord'
          siteUrl='https://discord.gg/wJKU5QEG6w'
          siteIcon='/discord-logo-1-1.png' 
          siteIconDescription='discord logo'
          />
          )}
        </div>
      </main>
    </>
  )
}
